# Generated by Django 4.2.11 on 2024-05-08 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course_feature_img_course_technologies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='technologies',
            new_name='techs',
        ),
    ]
