# Generated by Django 4.2.11 on 2024-05-08 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_technologies_course_techs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='feature_img',
            field=models.ImageField(null=True, upload_to='media/course_imgs/'),
        ),
    ]
