# Generated by Django 4.2.11 on 2024-05-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_teacher_bio_alter_chapter_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
    ]
