# Generated by Django 4.2.11 on 2024-05-19 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_studentcourseenrollment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name_plural': '4. Chapter'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': '3. Course'},
        ),
        migrations.AlterModelOptions(
            name='coursecategory',
            options={'verbose_name_plural': '2. Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': '5. Student'},
        ),
    ]
