# Generated by Django 4.2.11 on 2024-05-21 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_courserating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courserating',
            options={'verbose_name_plural': '7. Courses Rating'},
        ),
        migrations.RenameField(
            model_name='courserating',
            old_name='reviews',
            new_name='remarks',
        ),
    ]
