# Generated by Django 4.2.11 on 2024-05-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_courserating_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='profile_img',
            field=models.ImageField(null=True, upload_to='<django.db.models.fields.CharField>/profile_imgs/'),
        ),
    ]
