# Generated by Django 4.2.11 on 2024-07-21 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'verbose_name_plural': '10. Notifications'},
        ),
    ]
