# Generated by Django 4.2.11 on 2024-07-21 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_notification_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_creat_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Notification Created At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_for',
            field=models.CharField(max_length=200, verbose_name='Notification For'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_read_status',
            field=models.BooleanField(default=False, verbose_name='Notification Status?'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_text',
            field=models.TextField(null=True, verbose_name='Notification Text'),
        ),
    ]
