# Generated by Django 4.2.11 on 2024-07-21 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_notification_notif_creat_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notif_text',
        ),
    ]
