# Generated by Django 4.2.11 on 2024-07-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_notification_student_notification_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notif_subject',
            field=models.CharField(max_length=200, null=True, verbose_name='Notification Subject'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_creat_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Notification Created At'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_for',
            field=models.CharField(max_length=200, null=True, verbose_name='Notification For'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_read_status',
            field=models.BooleanField(default=False, null=True, verbose_name='Notification Status?'),
        ),
    ]
