# Generated by Django 4.2.11 on 2024-07-22 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_notification_notif_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassignment',
            name='student_status',
            field=models.BooleanField(default=False),
        ),
    ]
