# Generated by Django 4.2.11 on 2024-07-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_studentassignment_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_read_status',
            field=models.BooleanField(default=False, verbose_name='Notification Status?'),
        ),
    ]
