# Generated by Django 4.2.11 on 2024-08-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_coursequiz_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestions',
            name='ans3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='ans4',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
