# Generated by Django 4.2.11 on 2024-08-01 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_alter_quizquestions_ans3_alter_quizquestions_ans4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestions',
            old_name='questions',
            new_name='title',
        ),
    ]
