# Generated by Django 4.2.11 on 2024-08-01 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_rename_questions_quizquestions_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizquestions',
            old_name='title',
            new_name='questions',
        ),
    ]
